Repository Open-EO/openeo-api, pull requests merged in 2019-10, with the labels that each got.

#222 errors.json: add placeholders in message of CollectionNotFound and ServiceNotFound
  errors.json
Labels: documentation

#225 Support multiple OIDC providers (#201) and other Auth improvements
  CHANGELOG.md
  openapi.json
Labels: feedback required, user management

#224 STAC for job results (#131)
  CHANGELOG.md
  openapi.json
  tests/test_examples.py
Labels: job management, stac / ogc

#229 Updating to STAC 0.8.1
  CHANGELOG.md
  docs/collections.md
  openapi.json
Labels: data discovery, stac / ogc
