Repository Open-EO/openeo-api, pull requests merged in 2020-05, with the labels that each got.

#280 Documentation tweaks related to user defined processes and process graph parameters
  openapi.yaml
Labels: documentation

#282 Several clarifications
  openapi.yaml
Labels: documentation

#286 Link to process examples instead of inlining them. #285
  CHANGELOG.md
  openapi.yaml
Labels: process discovery

#283 Collection-level assets
  CHANGELOG.md
  openapi.yaml
Labels: data discovery

#284 User-defined process parameters are recursively defined
  CHANGELOG.md
  openapi.yaml
Labels: bug
