Repository Open-EO/openeo-api, pull requests merged in 2021-04, with the labels that each got.

#372 Clarified case-insensitivity
  CHANGELOG.md
  openapi.yaml
Labels: documentation

#366 Add `default_client_id` to OpenID Connect provider data
  CHANGELOG.md
  openapi.yaml
Labels: user management

#359 Support STAC Collections as Job Results
  CHANGELOG.md
  openapi.yaml
Labels: job management, platform, stac / ogc
